model:
  resume: False
  use_fp16: True
  amp: True
  lr: 1e-4
  embed_dim: 64
  params:
    lossconfig:
      adversarial: False
      epochs: 300
      warmup_epochs: 5
      kl_anneal: True
      kl_max_coeff: 0.01
      kl_const_coeff: 0.0001
      kl_const_portion: 0.0001
      kl_anneal_portion: 0.9
      disc_weight: 0.5
      sn_reg: True
      sn_reg_weight_decay: 1e-1
      sn_reg_weight_decay_anneal: True
      sn_reg_weight_decay_init: 5
      lr_scheduler: True
      save_and_sample_every: 25
      gradient_accumulate_every: 5

    ddconfig:
      double_z: True
      z_channels: 128
      resolution: 64 # need to match the resolution after pointnet encoder
      in_channels: 32 # need to match feature dimension after pointnet encoder
      out_ch: 64
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      hdbf_resolutions: [32, 16] # currently, only supports three decomposed BFs.
      inter_attn_resolutions: [64, 32, 16]
      dropout: 0.0
      attn_type: vanilla

    mlpconfig:
      in_ch: 3
      out_ch: 1
      ch: 256
      latent_dim: 64

data:
  domain: occupancy
  mode: train
  save_pth: ./save_path
  batch_size: 12
  conv_config: convocc/configs/pointcloud/shapenet_3plane.yaml
